# Generated by Django 2.1.5 on 2019-05-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190501_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategorySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('category_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.CategorySkill')),
            ],
        ),
        migrations.RemoveField(
            model_name='roomskill',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomskill',
            name='skill',
        ),
        migrations.AlterField(
            model_name='room',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='rooms', through='profiles.RoomCategorySkill', to='profiles.CategorySkill'),
        ),
        migrations.DeleteModel(
            name='RoomSkill',
        ),
        migrations.AddField(
            model_name='roomcategoryskill',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Room'),
        ),
    ]
