# Generated by Django 2.1.5 on 2019-05-07 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='skill',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='profiles.Skill'),
            preserve_default=False,
        ),
    ]
