# Generated by Django 2.1.5 on 2019-05-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_history_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Room'),
            preserve_default=False,
        ),
    ]
